apiVersion: v1
kind: Service
metadata:
  name: internal-app
  namespace: default
  labels:
    app: internal-app
spec:
  selector:
    app: internal-app
  ports:
    - port: 80
      targetPort: 8098
      protocol: TCP