apiVersion: v1
kind: Service
metadata:
  name: main-app
  namespace: default
  labels:
    app: main-app
spec:
  type: NodePort
  selector:
    app: main-app
  ports:
    - port: 80
      targetPort: 8090
      nodePort: 30002
      protocol: TCP