apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
spec:
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
        - name: main-app
          image: main-app:v1
          env:
            - name: SERVICE_URL
              value: "http://internal-app"
          imagePullPolicy: Never
          ports:
            - containerPort: 8090
              protocol: TCP