apiVersion: v1
kind: Service
metadata:
  name: simulator
  namespace: default
  labels:
    app: simulator
spec:
  selector:
    app: simulator
  ports:
    - port: 80
      targetPort: 8091
      protocol: TCP