apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
       - name: simulator
         image: simulator:v1
         env:
         - name: SERVICE_URL
           value: "http://internal-app"
         imagePullPolicy: Never
         ports:
         - containerPort: 8091
           protocol: TCP